### ISSUE TITLE
anguan2 下面使用该插件会报错 编译表失败

### ISSUE THREAD

**Issue by HJ520134** [IFmiss/d-audio#3]
ERROR in ./node_modules/d-audio/src/lib/d-audio.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import "node_modules/compass-mixins/lib/compass/css3";
@import "./font-icon/style.css";
@keyframes rotateMusicLogo {
  0% {
    transform: rotate(0);
  }
  50% {
    transform: rotate(180deg);
  }
  100% {
    transform: rotate(360deg);
  }
}
@-webkit-keyframes rotateMusicLogo {
  0% {
    transform: rotate(0);
  }
  50% {
    transform: rotate(180deg);
  }
  100% {
    transform: rotate(360deg);
  }
}
@-moz-keyframes rotateMusicLogo {
  0% {
    transform: rotate(0);
  }
  50% {
    transform: rotate(180deg);
  }
  100% {
    transform: rotate(360deg);
  }
}

// 添加blur模糊效果
// 如果不是绝对定位，父元素需要设置相对定位
// $blur 为模糊的数值
// $height 区域的高度
// $position 为位置 默认50%
@mixin blur($blur, $height, $position: 50%, $scale: 1.5) {
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        background-repeat: no-repeat;
        background-size: cover;
        background-position: $position;
        -webkit-filter: blur($blur);
        filter: blur($blur);
        -webkit-transform: scale($scale);
        transform: scale($scale);
        overflow: hidden;
        &::before{
                content: '';
                position: absolute;
                left: 0;
                top: 0;
                right: 0;
                bottom: 0;
                z-index: 1;
                background: rgba(0,0,0,0.1);
                transition: all 0.3s;
        }
        @if ($height == auto) {
                bottom: 0;
        }
        @else {
                height: $height;
        }
        &.draken{
                &::before{
                        background: rgba(0,0,0,0.3);
                }
        }
}

.audio-content{
  width: 100%;
  height: 100%;
  min-width: 240px;
  min-height: 50px;
  overflow: hidden;
  position: relative;
  @include transition(all 0.3s);
  -webkit-transform-origin: right center;
  -moz-transform-origin: right center;
  transform-origin: right center;
  @include border-radius(6px);
  @include user-select(none);
  @include translate3d(0,0,0);
  font-family: Arial, Helvetica, sans-serif;
  &.cricle{
    min-width: 50px;
    min-height: 50px;
    border-radius: 50%;
    .audio-detail{
      visibility: hidden;
      opacity: 0;
      .right-info{
        visibility: hidden;
        opacity: 0;
      }
    }
    .audio-cricle{
      visibility: visible;
      opacity: 1;
      z-index: 6;
      min-width: 50px;
      min-height: 50px;
    }
  }
  .audio-cricle{
    width: 50px;
    height: 50px;
    position: relative;
    visibility: hidden;
    overflow: hidden;
    @include transition(all 0.5s);
    opacity: 0;
    @include border-radius(50%);
    @include translate3d(0,0,0);
    -moz-animation: rotateMusicLogo 8s linear infinite;
    -webkit-animation: rotateMusicLogo 8s linear infinite;
    animation: rotateMusicLogo 8s linear infinite;
    -moz-animation-play-state: paused;
    -webkit-animation-play-state: paused;
    animation-play-state: paused;
    cursor: pointer;
    img{
      width: 100%;
      height: 100%;
    }
    &::before{
      content: '';
      position: absolute;
      top: 0;
      left: 0;
      bottom: 0;
      right: 0;
      border: 3px solid rgba(14, 90, 80, 0.397);
      @include border-radius(50%);
    }
    &.active{
      -moz-animation-play-state: running;
      -webkit-animation-play-state: running;
      animation-play-state: running;
    }
  }
  .audio-detail{
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    z-index: 5;
    display: flex;
    align-items: center;
    justify-content: center;
    visibility: visible;
    opacity: 1;
    @include border-radius(8px);
    @include transition(all 0.5s);
    @include translate3d(0,0,0);
    .left-config{
      flex: 0 0 90px;
      height: 100%;
      overflow: hidden;
      display: flex;
      align-items: center;
      padding: 0 5px 0 10px;
      box-sizing: border-box;
      i{
        display: block;
        width: 36px;
        height: 36px;
        background: rgba(0,0,0,0.2);
        @include transition(all 0.5s);
        @include border-radius(50%);
        color: rgba(255,255,255,0.6);
        text-align: center;
        line-height: 36px;
        font-size: 22px;
        cursor: pointer;
        &.next{
          width: 28px;
          height: 28px;
          margin-left: 10px;
          line-height: 28px;
          font-size: 10px;
        }
        &:hover{
          background: rgba(0,0,0,0.5);
        }
      }
    }
    .right-info{
      flex: 1 1 auto;
      height: 100%;
      overflow: hidden;
      color: #fff;
      display: flex;
      align-items: center;
      justify-content: center;
      flex-direction: column;
      box-sizing: border-box;
      padding: 0 10px 0 5px;
      visibility: visible;
      opacity: 1;
      @include transition(all 0.5s);
      .m-title{
        font-size: 16px;
        padding: 1px 0;
        margin: 0;
        font-weight: 200;
        text-overflow: ellipsis;
        overflow: hidden;
        white-space: nowrap;
        width: 100%;
        text-align: center;
      }
      .m-singer{
        font-weight: 200;
        padding: 1px 0;
        font-size: 12px;
        margin: 0;
        color: rgba(255,255,255,0.8);
        text-overflow: ellipsis;
        overflow: hidden;
        white-space: nowrap;
        width: 100%;
        text-align: center;
      }
    }
  }
  .audio-bg{
    position: absolute;
    z-index: 2;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    @include blur(10px, auto, center);
  }
  .audio-loading{
    position: absolute;
    z-index: 12;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: rgba(0, 0, 0, 0.52);
    display: flex;
    align-items: center;
    justify-content: center;
    visibility: hidden;
    @include transition(all 0.5s);
    opacity: 0;
    svg{
      width: 36px;
      height: 36px;
    }
    &.active{
      visibility: visible;
      opacity: 1;
    }
  }
  .audio-progress{
    position: absolute;
    left: 0;
    height: 1px;
    bottom: 0;
    width: 0;
    @include background(linear-gradient(to right, rgba(255, 56, 56, 0.1) 30%, rgba(255, 56, 56, 0.6)));
    @include transition(all 0.5s);
    z-index: 4;
  }
}
^
      File to import not found or unreadable: node_modules/compass-mixins/lib/compass/css3.
      in d:\Develop\MyGitHub\HWFGit\Angualr\node_modules\d-audio\src\lib\d-audio.scss (line 1, column 1)

**Comment by IFmiss** [comment]
需要安装 compass-mixins 的  你的依赖全部安装了吗？不行node_modules删了重新装一下
